version: "3.9"
services:
  goplay1:
    container_name: "goplay1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "9000:9000"
    depends_on:
      - mysql1
      - redis1
  mysql1:
    image: "mysql:8.0"
    container_name: mysql1
    restart: always
    ports:
    - "33061:3306"
    volumes:
      - ~/mysql/conf:/etc/mysql
      - ~/mysql/data:/var/lib/mysql
      - ~/mysql/mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxx
    command: #会和 entry-point 的 sh 脚本一起作用启动 mysqld
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
  redis1:
    image: "redis:6.2.3"
    container_name: redis1
    restart: always
    ports:
      - "63791:6379"
    volumes:
      - ~/redis/conf:/usr/local/etc/redis
      - ~/redis/data:/data
    command:
      redis-server
    #redis-server /usr/local/etc/redis/redis.conf